# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LYKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
 pod 'AFNetworking'
 pod 'Masonry', '~> 1.1.0'
 pod 'LYSegmentBar'
 pod 'FMDB'
end
