# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LYKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
 pod 'AFNetworking'
 pod 'Masonry', '~> 1.1.0'
 pod 'LYSegmentBar'
 pod 'FMDB'
 pod "GCDWebServer/WebUploader", "~> 3.0"
 pod 'SDWebImage', '4.2.0'
 pod 'YYModel', '~> 1.0.4'
 pod 'YYText','~> 1.0.7'
 pod 'CTMediator'
 pod 'YYCache'
end

#使用以下代码避免每次pod install,报错：Signing for "*.bundle" requires a development team.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
