# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LYKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
 pod 'AFNetworking'
 pod 'Masonry', '~> 1.1.0'
 pod 'LYSegmentBar'
 pod 'FMDB'
 pod "GCDWebServer/WebUploader", "~> 3.0"
 pod 'SDWebImage', '4.2.0'
 pod 'YYModel', '~> 1.0.4'
 pod 'YYText','~> 1.0.7'
end
